# Classification Workflow Configuration

# Data Preprocessing
preprocessing:
  lowercase: true
  remove_punctuation: false
  remove_extra_whitespace: true
  min_text_length: 10

# Feature Engineering
features:
  use_text_statistics: true
  use_embeddings: false  # Will be enabled when embedding models are available
  embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
  max_sequence_length: 512

# Model Configuration
models:
  baseline:
    - name: "logistic_regression"
      params:
        max_iter: 1000
        random_state: 42
        C: 1.0
    - name: "decision_tree"
      params:
        random_state: 42
        max_depth: 10
        min_samples_split: 5

# Training Configuration
training:
  test_size: 0.2
  validation_size: 0.1
  random_state: 42
  stratify: true
  cross_validation_folds: 5

# Evaluation Configuration
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
  per_class_metrics: true
  confusion_matrix: true
  classification_report: true

# Error Analysis
error_analysis:
  analyze_misclassifications: true
  top_confusions: 5
  save_misclassified_samples: true

# Output Configuration
output:
  save_model: true
  save_predictions: true
  save_evaluation_report: true
  save_feature_importance: true

# Feedback Loop Configuration
feedback:
  enable_active_learning: false
  uncertainty_threshold: 0.7
  samples_to_annotate: 10
