arms:
  - baseline
  - confidence_only
  - error_awareness_only
  - multiturn_only
  - full_system

human_eval:
  subset: subset_20
  temperature: 0.2
  max_turns: 2

gsm8k:
  dataset: data/smoke/gsm8k16.csv
  temperature: 0.2
  max_turns: 2

