runtime:
  demo_mode: true            # uses deterministic stub for tests
  max_turns: 3
  parallel_learners_k: 1
models:
  provider: "demo"           # "demo" | "openai" | "anthropic"
  temperature:
    learner_math: 0.3
    learner_facts: 0.6
    teacher: 0.0
paths:
  dataset: "data/math20.csv"
  traces_out: "outputs/traces.json"
